/**
 * Enterprise tool gateway: snapshot policy + live connector/grant checks.
 * Drive/Gmail/HTTP/KB reads are synchronous; writes enqueue a GatewayOperation.
 */
export {
  authorizeToolCall,
  type AuthorizeToolCallDeps,
  type AuthorizeToolCallInput,
  type AuthorizeToolCallResult,
  type LiveConnectorRow,
  type LiveGrantRow,
  type ToolCallPrincipal,
} from './authorize-tool-call'
export {
  invokeEnterpriseTool,
  authorizationLinkFields,
  type EnterpriseToolDeps,
  type EnterpriseToolMcpResult,
  type InputRequiredToolResult,
  type StartDelegatedAuthorization,
  type WriteConfirmInput,
  type WriteConfirmState,
} from './invoke-enterprise-tool'
export { asUuid, ENTERPRISE_TOOL_ERROR_MESSAGES, enterpriseToolErrorMessage, enterpriseToolErrorPayload } from './tool-error-messages'
export {
  ENTERPRISE_DRIVE_TOOLS,
  ENTERPRISE_DRIVE_WRITE_TOOLS,
  ENTERPRISE_GMAIL_TOOLS,
  ENTERPRISE_GMAIL_WRITE_TOOLS,
  ENTERPRISE_HTTP_TOOLS,
  ENTERPRISE_HTTP_WRITE_TOOLS,
  ENTERPRISE_KB_TOOLS,
  ENTERPRISE_TOOLS,
  ENTERPRISE_WRITE_TOOLS,
  GMAIL_CREATE_DRAFT_TOOL,
  GMAIL_GET_MESSAGE_TOOL,
  GMAIL_GET_THREAD_TOOL,
  GMAIL_LIST_DRAFTS_TOOL,
  GMAIL_LIST_LABELS_TOOL,
  GMAIL_MCP_INPUT_SCHEMAS,
  GMAIL_MODIFY_LABELS_TOOL,
  GMAIL_SEARCH_TOOL,
  GMAIL_SEND_TOOL,
  GMAIL_TRASH_TOOL,
  GOOGLE_DRIVE_CREATE_FOLDER_TOOL,
  GOOGLE_DRIVE_READ_FILE_TOOL,
  GOOGLE_DRIVE_SEARCH_TOOL,
  GOOGLE_DRIVE_UPLOAD_FILE_TOOL,
  GOOGLE_SHEETS_WRITE_RANGE_TOOL,
  HTTP_API_GET_ALL_TOOL,
  HTTP_API_GET_TOOL,
  HTTP_API_REQUEST_TOOL,
  KB_GET_DOCUMENT_TOOL,
  KB_GET_PAGE_TOOL,
  KB_INGEST_TOOL,
  KB_LIST_INDEX_TOOL,
  KB_SEARCH_TOOL,
  gmailGetMessageInputSchema,
  gmailGetThreadInputSchema,
  gmailListDraftsInputSchema,
  gmailListLabelsInputSchema,
  gmailSearchInputSchema,
  googleDriveCreateFolderInputSchema,
  googleDriveReadFileInputSchema,
  googleDriveSearchInputSchema,
  googleDriveUploadFileInputSchema,
  googleSheetsWriteRangeInputSchema,
  httpApiGetAllInputSchema,
  httpApiGetInputSchema,
  httpApiRequestInputSchema,
  kbGetDocumentInputSchema,
  kbGetPageInputSchema,
  kbIngestInputSchema,
  kbListIndexInputSchema,
  kbSearchInputSchema,
  isEnterpriseDriveTool,
  isEnterpriseDriveWriteTool,
  isEnterpriseGmailTool,
  isEnterpriseGmailWriteTool,
  isEnterpriseHttpTool,
  isEnterpriseHttpWriteTool,
  isEnterpriseKbTool,
  isEnterpriseTool,
  isEnterpriseWriteTool,
  schemaForEnterpriseDriveTool,
  schemaForEnterpriseKbTool,
  schemaForEnterpriseTool,
  type EnterpriseDriveTool,
  type EnterpriseDriveWriteTool,
  type EnterpriseGmailTool,
  type EnterpriseGmailWriteTool,
  type EnterpriseHttpTool,
  type EnterpriseKbTool,
  type EnterpriseTool,
  type EnterpriseWriteTool,
} from './tool-definitions'
