var R=require("./chunks/[turbopack]_runtime.js")("server/middleware.js")
R.c("server/chunks/node_modules_next_headers_009nr3b.js")
R.c("server/chunks/node_modules_next_00r2793._.js")
R.c("server/chunks/node_modules_@clerk_shared_dist_1n956ss._.js")
R.c("server/chunks/node_modules_@clerk_backend_dist_1jnp-5n._.js")
R.c("server/chunks/node_modules_@clerk_nextjs_dist_esm_13fzne8._.js")
R.c("server/chunks/node_modules_0f2nfyj._.js")
R.c("server/chunks/[root-of-the-server]__00skbfs._.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/middleware.js { INNER_MIDDLEWARE_MODULE => \"[project]/src/proxy.ts [middleware] (ecmascript)\" } [middleware] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/middleware.js { INNER_MIDDLEWARE_MODULE => \"[project]/src/proxy.ts [middleware] (ecmascript)\" } [middleware] (ecmascript)").exports
