var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/node_modules_next_dist_18cn2n6._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0b__2h-._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_1_kobm0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_0d323sd._.js")
R.c("server/chunks/ssr/node_modules_next_dist_server_route-modules_app-page_0qo_rmc._.js")
R.c("server/chunks/ssr/[externals]__12if52y._.js")
R.c("server/chunks/ssr/src_messages_0zwq71a._.js")
R.c("server/chunks/ssr/node_modules_1by2qoe._.js")
R.c("server/chunks/ssr/src_0_ee7s-._.js")
R.c("server/chunks/ssr/src_app_error_tsx_15dgtgq._.js")
R.c("server/chunks/ssr/src_1dm94-d._.js")
R.c("server/chunks/ssr/_205rbl-._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0p8s4lh._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/_1-4l-jh._.js")
R.c("server/chunks/ssr/[externals]__0qvnf3e._.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-page.js?page=/_not-found/page { METADATA_0 => \"[project]/src/app/icon.png.mjs { IMAGE => \\\"[project]/src/app/icon.png (static in ecmascript, tag client)\\\" } [app-rsc] (structured image object, ecmascript)\", METADATA_1 => \"[project]/src/app/apple-icon.png.mjs { IMAGE => \\\"[project]/src/app/apple-icon.png (static in ecmascript, tag client)\\\" } [app-rsc] (structured image object, ecmascript)\", MODULE_2 => \"[project]/src/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_3 => \"[project]/src/app/error.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_4 => \"[project]/src/app/loading.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_5 => \"[project]/src/app/not-found.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_6 => \"[project]/node_modules/next/dist/client/components/builtin/forbidden.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_7 => \"[project]/node_modules/next/dist/client/components/builtin/unauthorized.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_8 => \"[project]/src/app/global-error.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_9 => \"[project]/src/app/not-found.tsx [app-rsc] (ecmascript, Next.js Server Component)\" } [app-rsc] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-page.js?page=/_not-found/page { METADATA_0 => \"[project]/src/app/icon.png.mjs { IMAGE => \\\"[project]/src/app/icon.png (static in ecmascript, tag client)\\\" } [app-rsc] (structured image object, ecmascript)\", METADATA_1 => \"[project]/src/app/apple-icon.png.mjs { IMAGE => \\\"[project]/src/app/apple-icon.png (static in ecmascript, tag client)\\\" } [app-rsc] (structured image object, ecmascript)\", MODULE_2 => \"[project]/src/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_3 => \"[project]/src/app/error.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_4 => \"[project]/src/app/loading.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_5 => \"[project]/src/app/not-found.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_6 => \"[project]/node_modules/next/dist/client/components/builtin/forbidden.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_7 => \"[project]/node_modules/next/dist/client/components/builtin/unauthorized.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_8 => \"[project]/src/app/global-error.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_9 => \"[project]/src/app/not-found.tsx [app-rsc] (ecmascript, Next.js Server Component)\" } [app-rsc] (ecmascript)").exports
