import type { TemplateDescriptor } from './template-descriptor'

export const AGENTMAIL_TEMPLATE_KEY = 'agentmail'
export const AGENTMAIL_API_BASE = 'https://api.agentmail.eu/v0'

export const BUILTIN_CONNECTOR_TEMPLATES: TemplateDescriptor[] = [
  {
    key: 'google-workspace',
    connectorType: 'gmail',
    displayName: 'Gmail (felhasználói)',
    description:
      'Per-user delegált Gmail OAuth connector — a platform gmail_* eszközei ezen a connectoron futnak.',
    activationHelp: `A Gmail connector a platform Google OAuth alkalmazását használja (Platform · Beállítások → Google OAuth). Tenant szinten nem kell Client ID-t vagy Secretet megadni.

Aktiválás után a felhasználók a saját Google-fiókjukkal kötik be a postafiókot (Kapcsolt fiókok).`,
    baseUrl: 'https://gmail.googleapis.com',
    egressHosts: [
      'gmail.googleapis.com',
      'accounts.google.com',
      'oauth2.googleapis.com',
      'www.googleapis.com',
    ],
    authMethods: [
      {
        kind: 'user_delegated_oauth2',
        authUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
        tokenUrl: 'https://oauth2.googleapis.com/token',
        userInfoUrl: 'https://www.googleapis.com/oauth2/v2/userinfo',
        accountEmailField: 'email',
        offlineParams: { access_type: 'offline' },
        scopeTransform: 'gmailAlias',
      },
    ],
    scopeCatalog: [
      {
        value: 'gmail.modify',
        label: 'Olvasás + írás',
        description: 'Gmail olvasás, piszkozat és címkézés.',
        default: true,
      },
      {
        value: 'gmail.readonly',
        label: 'Csak olvasás',
        description: 'Gmail üzenetek és metaadatok olvasása.',
        default: false,
      },
      {
        value: 'gmail.send',
        label: 'Csak küldés',
        description: 'Email küldés a csatlakoztatott fiókból.',
        default: false,
      },
    ],
    endpoints: [
      {
        name: 'gmail_profile',
        method: 'GET',
        path: '/gmail/v1/users/me/profile',
        access: 'read',
        description: 'Read the connected Gmail profile.',
        default: true,
      },
      {
        name: 'gmail_messages',
        method: 'GET',
        path: '/gmail/v1/users/me/messages',
        access: 'read',
        description: 'List Gmail messages for the connected user.',
        default: true,
      },
    ],
    instanceFields: [],
  },
  {
    key: 'google-drive',
    connectorType: 'google_drive',
    displayName: 'Google Drive (felhasználói)',
    description:
      'Per-user delegált Google Drive OAuth connector — a platform google_drive_* eszközei ezen a connectoron futnak.',
    activationHelp: `A Google Drive connector a platform Google Drive OAuth alkalmazását használja (Platform · Beállítások → Google Drive OAuth). Tenant szinten nem kell Client ID-t vagy Secretet megadni.

Aktiválás után a felhasználók a saját Google-fiókjukkal kötik be a Drive-ot (Kapcsolt fiókok).`,
    baseUrl: 'https://www.googleapis.com',
    egressHosts: [
      'www.googleapis.com',
      'drive.googleapis.com',
      'accounts.google.com',
      'oauth2.googleapis.com',
    ],
    authMethods: [
      {
        kind: 'user_delegated_oauth2',
        authUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
        tokenUrl: 'https://oauth2.googleapis.com/token',
        userInfoUrl: 'https://www.googleapis.com/oauth2/v2/userinfo',
        accountEmailField: 'email',
        offlineParams: { access_type: 'offline' },
        scopeTransform: 'none',
      },
    ],
    scopeCatalog: [
      {
        value: 'https://www.googleapis.com/auth/drive.readonly',
        label: 'Csak olvasás',
        description: 'Teljes keresés és olvasás a user Google ACL-je szerint.',
        default: true,
      },
      {
        value: 'https://www.googleapis.com/auth/drive.file',
        label: 'Írás kijelölt fájlokon',
        description: 'Olvasás + írás app/Picker által kiválasztott fájlokon.',
        default: false,
      },
      {
        value: 'https://www.googleapis.com/auth/drive',
        label: 'Teljes olvasás + írás',
        description: 'Minden kezelhető fájl írása — csak admin engedéllyel.',
        default: false,
      },
    ],
    endpoints: [
      {
        name: 'drive_search',
        method: 'GET',
        path: '/drive/v3/files',
        access: 'read',
        description: 'Drive fájlok keresése és listázása.',
        default: true,
      },
      {
        name: 'drive_get_file',
        method: 'GET',
        path: '/drive/v3/files/{fileId}',
        access: 'read',
        description: 'Egy Drive fájl metaadatának lekérése.',
        default: true,
      },
      {
        name: 'drive_read_content',
        method: 'GET',
        path: '/drive/v3/files/{fileId}',
        access: 'read',
        description: 'Fájltartalom letöltése vagy exportálása.',
        default: true,
      },
      {
        name: 'drive_list_drives',
        method: 'GET',
        path: '/drive/v3/drives',
        access: 'read',
        description: 'Megosztott meghajtók listázása.',
        default: true,
      },
      {
        name: 'drive_create_folder',
        method: 'POST',
        path: '/drive/v3/files',
        access: 'write',
        description: 'Mappa létrehozása.',
        default: false,
      },
      {
        name: 'drive_upload',
        method: 'POST',
        path: '/upload/drive/v3/files',
        access: 'write',
        description: 'Fájl feltöltése.',
        default: false,
      },
      {
        name: 'drive_update',
        method: 'PATCH',
        path: '/drive/v3/files/{fileId}',
        access: 'write',
        description: 'Fájl metaadat vagy tartalom frissítése.',
        default: false,
      },
      {
        name: 'drive_copy',
        method: 'POST',
        path: '/drive/v3/files/{fileId}/copy',
        access: 'write',
        description: 'Fájl másolása.',
        default: false,
      },
      {
        name: 'drive_trash',
        method: 'PATCH',
        path: '/drive/v3/files/{fileId}',
        access: 'write',
        risk: 'danger',
        description: 'Fájl kukába helyezése (visszaállítható).',
        default: false,
      },
      {
        name: 'drive_share',
        method: 'POST',
        path: '/drive/v3/files/{fileId}/permissions',
        access: 'write',
        risk: 'danger',
        description: 'Megosztás konkrét userrel vagy grouppal.',
        default: false,
      },
    ],
    instanceFields: [],
  },
  {
    key: 'microsoft-365',
    displayName: 'Microsoft 365',
    description: 'Microsoft Graph delegated OAuth connector with explicit provider metadata.',
    connectorType: 'http_api',
    baseUrl: 'https://graph.microsoft.com',
    egressHosts: ['graph.microsoft.com', 'login.microsoftonline.com'],
    authMethods: [
      {
        kind: 'user_delegated_oauth2',
        authUrl: 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize',
        tokenUrl: 'https://login.microsoftonline.com/common/oauth2/v2.0/token',
        userInfoUrl: 'https://graph.microsoft.com/v1.0/me',
        accountEmailField: 'userPrincipalName',
        offlineParams: { prompt: 'consent' },
        scopeTransform: 'none',
      },
    ],
    scopeCatalog: [
      {
        value: 'offline_access',
        label: 'Offline access',
        description: 'Allow refresh tokens for delegated access.',
        default: true,
      },
      {
        value: 'User.Read',
        label: 'User profile',
        description: 'Read the connected user profile.',
        default: true,
      },
      {
        value: 'Mail.Read',
        label: 'Mail read',
        description: 'Read user mail through Microsoft Graph.',
        default: false,
      },
      {
        value: 'Mail.Send',
        label: 'Mail send',
        description: 'Send mail as the connected user.',
        default: false,
      },
    ],
    endpoints: [
      {
        name: 'me',
        method: 'GET',
        path: '/v1.0/me',
        access: 'read',
        description: 'Read the connected Microsoft Graph profile.',
        default: true,
      },
      {
        name: 'messages',
        method: 'GET',
        path: '/v1.0/me/messages',
        access: 'read',
        description: 'List mailbox messages for the connected user.',
        default: true,
      },
    ],
    instanceFields: [
      {
        name: 'clientId',
        label: 'OAuth client ID',
        type: 'string',
        required: true,
        target: 'auth.clientId',
      },
      {
        name: 'clientSecret',
        label: 'OAuth client secret',
        type: 'secret',
        required: true,
        secretAliasHint: 'microsoft-365-oauth-client-secret',
        target: 'auth.secretAliasSuggested',
      },
    ],
  },
  {
    key: 'jira-cloud',
    displayName: 'Jira Cloud',
    description: 'Atlassian Jira Cloud REST connector using an API token header.',
    connectorType: 'http_api',
    baseUrl: 'https://{siteHost}',
    egressHosts: ['{siteHost}'],
    authMethods: [{ kind: 'api_key', header: 'Authorization' }],
    scopeCatalog: [],
    endpoints: [
      {
        name: 'myself',
        method: 'GET',
        path: '/rest/api/3/myself',
        access: 'read',
        description: 'Read the authenticated Jira user.',
        default: true,
      },
      {
        name: 'search_issues',
        method: 'GET',
        path: '/rest/api/3/search',
        access: 'read',
        description: 'Search Jira issues with JQL.',
        default: true,
      },
      {
        name: 'create_issue',
        method: 'POST',
        path: '/rest/api/3/issue',
        access: 'write',
        description: 'Create a Jira issue.',
        default: false,
      },
    ],
    instanceFields: [
      {
        name: 'siteHost',
        label: 'Jira site host',
        type: 'string',
        required: true,
        validation: { format: 'host', pattern: '^[a-z0-9][a-z0-9.-]*\\.atlassian\\.net$' },
        target: 'egressHosts',
      },
      {
        name: 'apiToken',
        label: 'API token',
        type: 'secret',
        required: true,
        secretAliasHint: 'jira-cloud-api-token',
        target: 'auth.secretAliasSuggested',
      },
    ],
  },
  {
    key: 'slack',
    displayName: 'Slack',
    description: 'Slack Web API connector using a bot or user bearer token.',
    connectorType: 'http_api',
    baseUrl: 'https://slack.com',
    egressHosts: ['slack.com', 'www.slack.com'],
    authMethods: [{ kind: 'bearer' }],
    scopeCatalog: [],
    endpoints: [
      {
        name: 'auth_test',
        method: 'GET',
        path: '/api/auth.test',
        access: 'read',
        description: 'Validate the Slack token and read workspace identity.',
        default: true,
      },
      {
        name: 'conversations_list',
        method: 'GET',
        path: '/api/conversations.list',
        access: 'read',
        description: 'List Slack channels visible to the token.',
        default: true,
      },
      {
        name: 'chat_post_message',
        method: 'POST',
        path: '/api/chat.postMessage',
        access: 'write',
        description: 'Post a Slack message.',
        default: false,
      },
    ],
    instanceFields: [
      {
        name: 'botToken',
        label: 'Slack bearer token',
        type: 'secret',
        required: true,
        secretAliasHint: 'slack-bearer-token',
        target: 'auth.secretAliasSuggested',
      },
    ],
  },
  {
    key: AGENTMAIL_TEMPLATE_KEY,
    connectorType: 'http_api',
    displayName: 'AgentMail (agent saját postafiókja)',
    description:
      'Az agent saját e-mail címe az AgentMailben (EU régió): a saját nevében küld, olvas és válaszol. Nem a felhasználó postafiókja — arra a Gmail (felhasználói) kapcsolat való.',
    activationHelp: `Ezt a kapcsolatot a Konnektorok → Agent postafiókok oldalon állítod be, nem ebben a varázslóban.

1. Hozz létre API kulcsot az AgentMail konzolban, EU régiós (api.agentmail.eu) szervezetben.
2. Az Agent postafiókok oldalon add meg egyszer — a platform titkosítva tárolja.
3. Hozz létre vagy köss be postafiókot; a platform minden postafiókhoz külön, csak arra a postafiókra érvényes (olvasás + küldés) kulcsot generál.
4. Válaszd ki, melyik agent használhatja. Minden kimenő levél emberi jóváhagyás után megy ki.`,
    baseUrl: `${AGENTMAIL_API_BASE}/inboxes/{inboxId}`,
    egressHosts: ['api.agentmail.eu'],
    authMethods: [{ kind: 'bearer' }],
    scopeCatalog: [],
    endpoints: [
      {
        name: 'list_messages',
        method: 'GET',
        path: '/messages',
        access: 'read',
        description:
          'A saját postafiók leveleinek listája (legújabb elöl). Query: limit, page_token, labels (pl. received, sent, unread).',
        default: true,
      },
      {
        name: 'get_message',
        method: 'GET',
        path: '/messages/{message_id}',
        access: 'read',
        description: 'Egy levél teljes tartalma (feladó, címzettek, tárgy, text/html, thread_id).',
        default: true,
      },
      {
        name: 'list_threads',
        method: 'GET',
        path: '/threads',
        access: 'read',
        description: 'Levélváltások listája. Query: limit, page_token, labels.',
        default: true,
      },
      {
        name: 'get_thread',
        method: 'GET',
        path: '/threads/{thread_id}',
        access: 'read',
        description: 'Egy levélváltás összes üzenete időrendben.',
        default: true,
      },
      {
        name: 'send_message',
        method: 'POST',
        path: '/messages/send',
        access: 'write',
        description:
          'Új levél küldése a saját címedről. Body: {"to":["cimzett@example.com"],"subject":"...","text":"..."}; opcionális: cc, bcc, html, reply_to. Emberi jóváhagyás után megy ki.',
        default: true,
      },
      {
        name: 'reply_to_message',
        method: 'POST',
        path: '/messages/{message_id}/reply',
        access: 'write',
        description:
          'Válasz egy beérkezett levélre ugyanabban a levélváltásban. Body: {"text":"..."}; opcionális: html, reply_all (true = mindenkinek), cc, bcc. Emberi jóváhagyás után megy ki.',
        default: true,
      },
    ],
    instanceFields: [],
    rateLimit: { rps: 2, burst: 5 },
  },
]
