#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

# ── Fixed inputs for this project ────────────────────────────────────────
PROJECT_ID="enterprise-ai-demo"
REGION="europe-west4"
SA_ID="eai-healthcheck-runner"
SA_EMAIL="${SA_ID}@${PROJECT_ID}.iam.gserviceaccount.com"
KEY_DIR="${HOME}/.config/eai-healthcheck"
KEY_PATH="${KEY_DIR}/gcp-runner-key.json"
ZSHRC="${HOME}/.zshrc"
ROLES=(
  "roles/logging.viewer"
  "roles/monitoring.viewer"
  "roles/run.viewer"
  "roles/firebaseapphosting.viewer"
)
# Prod DB secret name (from apphosting.yaml). The platform reads DATABASE_URL
# from this Firebase App Hosting secret.
PROD_DB_SECRET="PLATFORM_DATABASE_URL"
# Dev DB URL lives in the local env file, relative to repo root.
DEV_ENV_FILE="app/.env.local"

banner "Enterprise AI — health-check access setup"
say "This wires up two things the daily health-check needs:"
note "  1. A dedicated, read-only GCP service account so log/metric reads no"
note "     longer ride on your personal gcloud token (which expires)."
note "  2. pg_stat_statements on the Neon dev + prod databases, so future"
note "     runs can actually see slow queries."
say ""
say "Run this from the repo root. It calls gcloud / firebase / psql for you and"
say "asks before every change. Nothing is written to the production app itself."

# ────────────────────────────────────────────────────────────────────────
stage "gcloud: sign in and select the project"
say "First we make sure your own gcloud session is valid — the health-check"
say "found it expired, and you need it to create the service account."
if gcloud auth print-access-token >/dev/null 2>&1; then
  step "Existing gcloud session is valid — no sign-in needed."
else
  step "Your gcloud session is expired. A browser window will open to sign in."
  pause "Press Enter to run 'gcloud auth login'."
  gcloud auth login
fi
gcloud config set project "$PROJECT_ID" >/dev/null
ACTIVE_ACCT="$(gcloud config get-value account 2>/dev/null || echo '?')"
step "Active account: ${ACTIVE_ACCT}"
step "Project set to: ${PROJECT_ID}"
say ""
say "You need 'Owner' or 'IAM Admin' + 'Service Account Admin' on this project"
say "for the next stages. If you don't, stop here and ask whoever does."
pause "Press Enter to continue."

# ────────────────────────────────────────────────────────────────────────
stage "Create the service account"
say "Name: ${SA_EMAIL}"
if gcloud iam service-accounts describe "$SA_EMAIL" --project "$PROJECT_ID" >/dev/null 2>&1; then
  step "Service account already exists — skipping creation."
else
  if confirm "Create service account '${SA_ID}'?"; then
    gcloud iam service-accounts create "$SA_ID" \
      --project "$PROJECT_ID" \
      --display-name "EAI daily health-check (read-only)" \
      --description "Non-interactive read-only access for the daily SRE/FinOps health-check routine."
    step "Created ${SA_EMAIL}"
  else
    SKIPPED+=("service account ${SA_EMAIL} not created — nothing else will work")
    warn "Skipped. Re-run this wizard when you can create it."
    finish; exit 0
  fi
fi

# ────────────────────────────────────────────────────────────────────────
stage "Grant read-only roles"
say "These are all *viewer* roles — no write, no delete, no secret access:"
for r in "${ROLES[@]}"; do note "  - $r"; done
say ""
if confirm "Bind these ${#ROLES[@]} roles to ${SA_ID} on ${PROJECT_ID}?"; then
  for r in "${ROLES[@]}"; do
    if gcloud projects add-iam-policy-binding "$PROJECT_ID" \
        --member "serviceAccount:${SA_EMAIL}" \
        --role "$r" \
        --condition=None >/dev/null; then
      step "granted $r"
    else
      SKIPPED+=("role $r not granted (grant it in IAM console)")
      warn "could not grant $r"
    fi
  done
else
  SKIPPED+=("roles not granted to ${SA_EMAIL}")
  warn "Skipped role binding."
fi

# ────────────────────────────────────────────────────────────────────────
stage "Create the key and install it locally"
say "The key is a JSON file. Treat it like a password:"
note "  - stored at ${KEY_PATH} (outside the repo, chmod 600)"
note "  - rotate it every ~90 days (re-run this wizard)"
note "  - if it leaks, run: gcloud iam service-accounts keys delete <id> --iam-account ${SA_EMAIL}"
say ""
say "Some orgs block service-account key creation by policy. If that happens,"
say "this stage will say so and the wizard will fall through to a fallback."
say ""
mkdir -p "$KEY_DIR"; chmod 700 "$KEY_DIR"
if [[ -f "$KEY_PATH" ]] && ! confirm "A key file already exists at ${KEY_PATH}. Replace it?"; then
  step "Keeping the existing key file."
else
  if confirm "Create a new key for ${SA_ID}?"; then
    if gcloud iam service-accounts keys create "$KEY_PATH" \
        --iam-account "$SA_EMAIL" --project "$PROJECT_ID"; then
      chmod 600 "$KEY_PATH"
      step "Wrote key to ${KEY_PATH}"
    else
      warn "Key creation failed (likely org policy iam.disableServiceAccountKeyCreation)."
      SKIPPED+=("SA key not created — see fallback note below")
      note "Fallback options, in order of preference:"
      note "  a) Ask an org admin to grant an exception, or to create the key for"
      note "     ${SA_EMAIL} and hand you the JSON; drop it at ${KEY_PATH} (chmod 600)."
      note "  b) Keep using your user account, but refresh it on a schedule:"
      note "     add 'gcloud auth login --no-launch-browser' to a weekly reminder."
      note "  c) Use impersonation instead of a key: grant your user"
      note "     roles/iam.serviceAccountTokenCreator on ${SA_EMAIL}, then the"
      note "     health-check runs: gcloud ... --impersonate-service-account=${SA_EMAIL}"
      pause "Press Enter to continue to verification (it will use whatever auth is active)."
    fi
  fi
fi

if [[ -f "$KEY_PATH" ]]; then
  # Register the SA with the gcloud CLI (does NOT change your default account).
  gcloud auth activate-service-account "$SA_EMAIL" --key-file "$KEY_PATH" --project "$PROJECT_ID" >/dev/null 2>&1 || \
    warn "activate-service-account reported an issue; the key file is still usable via GOOGLE_APPLICATION_CREDENTIALS."
  # Make sure your interactive default account is restored as active.
  if [[ "${ACTIVE_ACCT:-}" != "?" && -n "${ACTIVE_ACCT:-}" ]]; then
    gcloud config set account "$ACTIVE_ACCT" >/dev/null 2>&1 || true
  fi
  step "Registered ${SA_EMAIL} with gcloud (your default account is unchanged)."

  # Idempotently install env vars in ~/.zshrc so the scheduled task's shell
  # (initialised from your profile) picks them up.
  MARK_START="# >>> eai-healthcheck gcp access >>>"
  MARK_END="# <<< eai-healthcheck gcp access <<<"
  touch "$ZSHRC"
  tmp="$(mktemp)"
  awk -v s="$MARK_START" -v e="$MARK_END" '
    $0==s {skip=1; next} $0==e {skip=0; next} !skip {print}
  ' "$ZSHRC" > "$tmp"
  {
    cat "$tmp"
    printf '%s\n' "$MARK_START"
    printf 'export GOOGLE_APPLICATION_CREDENTIALS="%s"\n' "$KEY_PATH"
    printf 'export EAI_HEALTHCHECK_GCP_SA="%s"\n' "$SA_EMAIL"
    printf 'export CLOUDSDK_CORE_PROJECT="%s"\n' "$PROJECT_ID"
    printf '%s\n' "$MARK_END"
  } > "$ZSHRC"
  rm -f "$tmp"
  step "Added GOOGLE_APPLICATION_CREDENTIALS + EAI_HEALTHCHECK_GCP_SA to ${ZSHRC}"
  note "Open a new terminal (or 'source ~/.zshrc') for these to take effect."
fi

# ────────────────────────────────────────────────────────────────────────
stage "Verify GCP read access"
say "Reading one log entry, one metric, and the Cloud Run service list with"
say "the service-account identity (falls back to your user account if no key)."
AUTH_ARG=()
if [[ -f "$KEY_PATH" ]] && gcloud auth list --filter="account:${SA_EMAIL}" --format="value(account)" 2>/dev/null | grep -q "$SA_EMAIL"; then
  AUTH_ARG=(--account "$SA_EMAIL")
  step "Verifying as ${SA_EMAIL}"
else
  step "Verifying as ${ACTIVE_ACCT} (service-account key not active)"
fi

OK=1
if gcloud logging read 'severity>=DEFAULT' --project "$PROJECT_ID" --limit 1 --freshness 30d "${AUTH_ARG[@]}" >/dev/null 2>&1; then
  step "logging.read  ✓"
else
  step "logging.read  ✗"; OK=0
fi
if gcloud run services list --project "$PROJECT_ID" --region "$REGION" "${AUTH_ARG[@]}" >/dev/null 2>&1; then
  step "run.services.list  ✓"
else
  step "run.services.list  ✗"; OK=0
fi
if TOKEN="$(gcloud auth print-access-token "${AUTH_ARG[@]}" 2>/dev/null)" && \
   curl -s -o /dev/null -w '%{http_code}' -H "Authorization: Bearer ${TOKEN}" \
     "https://monitoring.googleapis.com/v3/projects/${PROJECT_ID}/metricDescriptors?pageSize=1" | grep -q '^200$'; then
  step "monitoring.read  ✓"
else
  step "monitoring.read  ✗"; OK=0
fi
if [[ "$OK" -eq 1 ]]; then
  step "All three read checks passed."
else
  warn "One or more checks failed. If roles were just granted, wait 1-2 min for"
  warn "IAM propagation and re-run this stage."
  SKIPPED+=("GCP read verification did not fully pass — re-check IAM bindings")
fi
pause "Press Enter to move on to the database stage."

# ────────────────────────────────────────────────────────────────────────
stage "Enable pg_stat_statements on the Neon DEV database"
say "Source: ${DEV_ENV_FILE} → DATABASE_URL"
DEV_URL=""
if [[ -f "$DEV_ENV_FILE" ]]; then
  DEV_URL="$(grep -E '^DATABASE_URL=' "$DEV_ENV_FILE" | head -1 | sed 's/^DATABASE_URL=//; s/^"//; s/"$//')" || true
fi
if [[ -z "$DEV_URL" ]]; then
  warn "Could not read DATABASE_URL from ${DEV_ENV_FILE}."
  ask_secret DEV_URL "Paste the Neon DEV connection string (postgresql://...):"
fi
if [[ -n "$DEV_URL" ]]; then
  say "This runs: CREATE EXTENSION IF NOT EXISTS pg_stat_statements;"
  say "It is additive and safe to run repeatedly."
  if confirm "Run it against the DEV database now?"; then
    if psql "$DEV_URL" -v ON_ERROR_STOP=1 -X -q \
         -c "SET statement_timeout='30s';" \
         -c "CREATE EXTENSION IF NOT EXISTS pg_stat_statements;" \
         -c "SELECT count(*) AS statements_tracked FROM pg_stat_statements;" ; then
      step "DEV: pg_stat_statements is enabled and returning rows."
    else
      warn "Failed. On Neon the library is normally preloaded; if it complains"
      warn "about shared_preload_libraries, enable it in the Neon Console:"
      note "  Neon Console → your project → Settings → (Compute / Postgres settings)"
      note "  add 'pg_stat_statements' to preloaded libraries, then re-run."
      note "  Docs: https://neon.tech/docs/extensions/pg_stat_statements"
      SKIPPED+=("DEV pg_stat_statements not enabled")
    fi
  fi
else
  SKIPPED+=("DEV database URL unknown — pg_stat_statements not enabled")
fi

# ────────────────────────────────────────────────────────────────────────
stage "Enable pg_stat_statements on the Neon PROD database"
warn "This is the ONLY change that touches production. It is a one-time,"
warn "additive DDL (CREATE EXTENSION). No app data is read or modified."
say ""
say "The prod connection string is pulled from the Firebase App Hosting secret"
say "'${PROD_DB_SECRET}' and is never printed by this wizard."
if ! confirm "Proceed with the production database?"; then
  SKIPPED+=("PROD pg_stat_statements not enabled (you declined)")
  warn "Skipped production. Re-run this wizard any time to do just this stage."
  finish; exit 0
fi
PROD_URL="$(firebase apphosting:secrets:access "$PROD_DB_SECRET" --project "$PROJECT_ID" 2>/dev/null || true)"
PROD_URL="${PROD_URL%$'\n'}"
if [[ -z "$PROD_URL" ]]; then
  warn "Could not read the secret via firebase CLI."
  say "Get it manually with:"
  note "  firebase apphosting:secrets:access ${PROD_DB_SECRET} --project ${PROJECT_ID}"
  ask_secret PROD_URL "Paste the Neon PROD connection string (postgresql://...):"
  PROD_URL="${PROD_URL%$'\n'}"
fi
if [[ -z "$PROD_URL" ]]; then
  SKIPPED+=("PROD database URL unavailable — pg_stat_statements not enabled")
else
  if psql "$PROD_URL" -v ON_ERROR_STOP=1 -X -q \
       -c "SET statement_timeout='30s';" \
       -c "CREATE EXTENSION IF NOT EXISTS pg_stat_statements;" \
       -c "SELECT current_database() AS db, count(*) AS statements_tracked FROM pg_stat_statements;" ; then
    step "PROD: pg_stat_statements is enabled and returning rows."
    note "It starts empty and fills as queries run. The next health-check"
    note "(2026-09-09) will have real slow-query data to rank."
  else
    warn "Failed against production. Same fix as dev: check the Neon Console"
    warn "preloaded-libraries setting for the PROD project, then re-run."
    note "  Docs: https://neon.tech/docs/extensions/pg_stat_statements"
    SKIPPED+=("PROD pg_stat_statements not enabled — check Neon Console setting")
  fi
fi
unset PROD_URL DEV_URL

finish
say "Follow-ups (code changes, not part of this wizard):"
note "  - Point ops/tools/logq.mjs + the health-check SKILL at the service"
note "    account: prefer ADC (GOOGLE_APPLICATION_CREDENTIALS) or pass"
note "    'gcloud --account \$EAI_HEALTHCHECK_GCP_SA ...' instead of the"
note "    firebase-tools token hack."
note "  - Add a calendar reminder to rotate the SA key (~90 days)."
