// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/[locale]" | "/[locale]/gtc" | "/[locale]/privacy" | "/connectors/oauth/done" | "/control-plane" | "/control-plane/account" | "/control-plane/agents" | "/control-plane/agents/[agentId]" | "/control-plane/agents/new" | "/control-plane/audit" | "/control-plane/connectors" | "/control-plane/dashboard" | "/control-plane/get-started" | "/control-plane/iam" | "/control-plane/iam/redeem" | "/control-plane/knowledge" | "/control-plane/menu-access" | "/control-plane/operations" | "/control-plane/pending" | "/control-plane/platform" | "/control-plane/platform/iam" | "/control-plane/platform/settings" | "/control-plane/platform/tenants" | "/control-plane/projects" | "/control-plane/provisioning" | "/control-plane/provisioning/agentmail" | "/control-plane/settings" | "/control-plane/skills" | "/sign-in/[[...sign-in]]" | "/sign-up/[[...sign-up]]"
type AppRouteHandlerRoutes = "/.well-known/oauth-authorization-server" | "/.well-known/oauth-protected-resource/[[...path]]" | "/api/connectors/oauth/callback" | "/api/control-plane/skills/versions/[versionId]/export" | "/api/healthz" | "/api/mcp/[tenantSlug]" | "/api/metrics" | "/api/readyz" | "/api/webhooks/clerk"
type PageRoutes = never
type LayoutRoutes = "/" | "/[locale]" | "/control-plane"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/.well-known/oauth-authorization-server": {}
  "/.well-known/oauth-protected-resource/[[...path]]": { "path"?: string[]; }
  "/[locale]": { "locale": string; }
  "/[locale]/gtc": { "locale": string; }
  "/[locale]/privacy": { "locale": string; }
  "/api/connectors/oauth/callback": {}
  "/api/control-plane/skills/versions/[versionId]/export": { "versionId": string; }
  "/api/healthz": {}
  "/api/mcp/[tenantSlug]": { "tenantSlug": string; }
  "/api/metrics": {}
  "/api/readyz": {}
  "/api/webhooks/clerk": {}
  "/connectors/oauth/done": {}
  "/control-plane": {}
  "/control-plane/account": {}
  "/control-plane/agents": {}
  "/control-plane/agents/[agentId]": { "agentId": string; }
  "/control-plane/agents/new": {}
  "/control-plane/audit": {}
  "/control-plane/connectors": {}
  "/control-plane/dashboard": {}
  "/control-plane/get-started": {}
  "/control-plane/iam": {}
  "/control-plane/iam/redeem": {}
  "/control-plane/knowledge": {}
  "/control-plane/menu-access": {}
  "/control-plane/operations": {}
  "/control-plane/pending": {}
  "/control-plane/platform": {}
  "/control-plane/platform/iam": {}
  "/control-plane/platform/settings": {}
  "/control-plane/platform/tenants": {}
  "/control-plane/projects": {}
  "/control-plane/provisioning": {}
  "/control-plane/provisioning/agentmail": {}
  "/control-plane/settings": {}
  "/control-plane/skills": {}
  "/sign-in/[[...sign-in]]": { "sign-in"?: string[]; }
  "/sign-up/[[...sign-up]]": { "sign-up"?: string[]; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/[locale]": never
  "/control-plane": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
