// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/[locale]/gtc/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/gtc">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/gtc/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/privacy">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/connectors/oauth/done/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/connectors/oauth/done">> = Specific
  const handler = {} as typeof import("../../../src/app/connectors/oauth/done/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/control-plane/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/control-plane/account">> = Specific
  const handler = {} as typeof import("../../../src/app/control-plane/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/control-plane/agents/[agentId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/control-plane/agents/[agentId]">> = Specific
  const handler = {} as typeof import("../../../src/app/control-plane/agents/[agentId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/control-plane/agents/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/control-plane/agents/new">> = Specific
  const handler = {} as typeof import("../../../src/app/control-plane/agents/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/control-plane/agents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/control-plane/agents">> = Specific
  const handler = {} as typeof import("../../../src/app/control-plane/agents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/control-plane/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/control-plane/audit">> = Specific
  const handler = {} as typeof import("../../../src/app/control-plane/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/control-plane/connectors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/control-plane/connectors">> = Specific
  const handler = {} as typeof import("../../../src/app/control-plane/connectors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/control-plane/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/control-plane/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/control-plane/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/control-plane/get-started/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/control-plane/get-started">> = Specific
  const handler = {} as typeof import("../../../src/app/control-plane/get-started/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/control-plane/iam/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/control-plane/iam">> = Specific
  const handler = {} as typeof import("../../../src/app/control-plane/iam/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/control-plane/iam/redeem/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/control-plane/iam/redeem">> = Specific
  const handler = {} as typeof import("../../../src/app/control-plane/iam/redeem/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/control-plane/knowledge/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/control-plane/knowledge">> = Specific
  const handler = {} as typeof import("../../../src/app/control-plane/knowledge/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/control-plane/menu-access/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/control-plane/menu-access">> = Specific
  const handler = {} as typeof import("../../../src/app/control-plane/menu-access/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/control-plane/operations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/control-plane/operations">> = Specific
  const handler = {} as typeof import("../../../src/app/control-plane/operations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/control-plane/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/control-plane">> = Specific
  const handler = {} as typeof import("../../../src/app/control-plane/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/control-plane/pending/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/control-plane/pending">> = Specific
  const handler = {} as typeof import("../../../src/app/control-plane/pending/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/control-plane/platform/iam/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/control-plane/platform/iam">> = Specific
  const handler = {} as typeof import("../../../src/app/control-plane/platform/iam/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/control-plane/platform/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/control-plane/platform">> = Specific
  const handler = {} as typeof import("../../../src/app/control-plane/platform/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/control-plane/platform/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/control-plane/platform/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/control-plane/platform/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/control-plane/platform/tenants/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/control-plane/platform/tenants">> = Specific
  const handler = {} as typeof import("../../../src/app/control-plane/platform/tenants/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/control-plane/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/control-plane/projects">> = Specific
  const handler = {} as typeof import("../../../src/app/control-plane/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/control-plane/provisioning/agentmail/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/control-plane/provisioning/agentmail">> = Specific
  const handler = {} as typeof import("../../../src/app/control-plane/provisioning/agentmail/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/control-plane/provisioning/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/control-plane/provisioning">> = Specific
  const handler = {} as typeof import("../../../src/app/control-plane/provisioning/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/control-plane/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/control-plane/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/control-plane/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/control-plane/skills/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/control-plane/skills">> = Specific
  const handler = {} as typeof import("../../../src/app/control-plane/skills/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/sign-in/[[...sign-in]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-in/[[...sign-in]]">> = Specific
  const handler = {} as typeof import("../../../src/app/sign-in/[[...sign-in]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/sign-up/[[...sign-up]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-up/[[...sign-up]]">> = Specific
  const handler = {} as typeof import("../../../src/app/sign-up/[[...sign-up]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/.well-known/oauth-authorization-server/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/.well-known/oauth-authorization-server">> = Specific
  const handler = {} as typeof import("../../../src/app/.well-known/oauth-authorization-server/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/.well-known/oauth-protected-resource/[[...path]]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/.well-known/oauth-protected-resource/[[...path]]">> = Specific
  const handler = {} as typeof import("../../../src/app/.well-known/oauth-protected-resource/[[...path]]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/connectors/oauth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/connectors/oauth/callback">> = Specific
  const handler = {} as typeof import("../../../src/app/api/connectors/oauth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/control-plane/skills/versions/[versionId]/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/control-plane/skills/versions/[versionId]/export">> = Specific
  const handler = {} as typeof import("../../../src/app/api/control-plane/skills/versions/[versionId]/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/healthz/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/healthz">> = Specific
  const handler = {} as typeof import("../../../src/app/api/healthz/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/mcp/[tenantSlug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mcp/[tenantSlug]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/mcp/[tenantSlug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/metrics">> = Specific
  const handler = {} as typeof import("../../../src/app/api/metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/readyz/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/readyz">> = Specific
  const handler = {} as typeof import("../../../src/app/api/readyz/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/webhooks/clerk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/clerk">> = Specific
  const handler = {} as typeof import("../../../src/app/api/webhooks/clerk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/[locale]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/control-plane/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/control-plane">> = Specific
  const handler = {} as typeof import("../../../src/app/control-plane/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
